[build]
  command = "pip install -r requirements.txt && python -m pygbag main.py --width 1280 --height 720 --name 'Ashley\\'s Asteroids' --optimize --out dist && ls -la dist/"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"