# This site is now built via GitHub Actions
# No build command needed - just deploy the pre-built files

[build]
  publish = "dist"
  ignore = "exit 0"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"