[build]
  command = "python -m pygbag main.py --width 1280 --height 720 --name 'Ashley\\'s Asteroids'"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"